---
version: "2.0"

services:
  app:
    image: dimokus88/paloma:0.3.2
    env:     
     - "MONIKER=NODE_NAME" #имя ноды (Если нетрудно, укажите в имени ноды Akash, например:DimokusAkash). node name (If it is not difficult, specify Akash in the node name, for example:DimokusAkash). 
     - "MNEMONIC=YOUR_WALLET_MNEMONIC" # seed phrase from the Paloma wallet. seed фраза от кошелька Paloma.
     - "LINK_KEY=LINK_TO_PRIV_VALIDATOR_KEY_JSON_DDOWNLOAD" # Ссылка на размещенный pirv-validator_key.json (прямое скачивание). Подойдет и от других тестнетов на базе Cosmos. link to the posted pirv-validator_key.json (direct download). It will also work from other Cosmos-based testnets.
     - "gitrep=https://github.com/palomachain/paloma/releases/download/v0.2.5-prealpha/paloma_0.2.5-prealpha_Linux_x86_64.tar.gz"
     - "SNAP_RPC=http://165.227.75.192:26657"
     - "PEER=ae611ea23c874ffba047f3d933509087e1ed90ad@86.32.74.154:26657,2de64ce284c5ef38e42190daa0f2e2b055b37e1b@165.227.75.192:26656"
     #- "addrbook=https://raw.githubusercontent.com/palomachain/testnet/master/paloma-testnet-6/addrbook.json"
     - "autodelegate=no"
     - "SHIFT=2000"
     
    expose:
      - port: 80
        as: 80
        to:
          - global: true
      - port: 22
        as: 22
        to:
          - global: true
        
profiles:
  compute:
    app:
      resources:
        cpu:
          units: 2.0
        memory:
          size: 4Gi
        storage:
          size: 40Gi
        
        
  placement:
    akash: 
      attributes:
        host: akash
      signedBy:
        anyOf:
            
      pricing:
        app:
          denom: uakt
          amount: 1000
deployment:
  app:
    akash:
      profile: app
      count: 1 
